language: ruby
cache:
- bundler
- yarn
node_js: '8'
rvm:
- 2.4.1
services:
- postgresql
env:
- RAILS_ENV=test
install:
- bundle install
- nvm install stable && nvm alias default stable
- npm install npm@latest -g
- npm install -g yarn
- npm --version
- yarn install
before_script:
- cp config/database.travis.yml config/database.yml
- cp .env.travis .env
script:
- bundle exec rake db:test:prepare
- bundle exec rspec
- yarn run lint
notifications:
  slack:
    secure: dDCUvZabKmfOH6acVGvaVG+0H9T8lcrpo3MALcOYy9dn429wGc+ich4Rf9lw3tZmTWlo77Ndfx3zWKevPOa2hMA1zN732DhK2M7NQM9muv+BPAlMnPG+bAda+/U29M/aKLqsfTHuBp9Z1BReixQTW8uhX/2KDNTDAp2FeBbC3ruwsFxTX0Bo4R8peoKnyYQwEI1EmtZFTh4tc7RflwhGkpQPePhrKlu/xYG60yVZ0H83n6/y5Mu+Kmx6SXIa4RWywoR+tbYWkRWEkimBzYiRUcMQJA5E2Uq+k5LWc4wIhY8COSjHnyEYVAae0jx9ehYaDPsQ6Db0k37fYL+wkpIpCmwMx3bqhQE/BmMdpQCoDUZvx42nNvhvg4Jh/ykDwi7vs6XFaJ+xg8Ne5GcHjxAfpSJZiPPZPM01K3akHBbATVdRDgQXdgpQFs7d8WcEqLh/7CHPRO23jnyYAcDcP7Lm0WLsY+yvR4nRORLT0LPqHGZexwTQGmzVo+HyCk1K9Q5Xchksydv2wjv/oxWagG16Ybm3tnSZXjeGSt5/yt+Kue1E9jhIgFPmzedb8nc5Y0Ido7nB0tx+E66L0b9iYX0jfQ61nd4frLlAH93mJ0gPIGEKf7vP6XAyihXwG745pcjiEQv5aXmcaqh9kLK9xNLHioOBjQGeoXkmacvoROeb3mU=
