version: '3.3'
services:
  web:
    image: mbellgb/hatch-site-dev # assumes image is on docker hub
    build:
      dockerfile: ./Dockerfile
    command: ["sh", "run-dev.sh"]
    environment:
      - RAILS_ENV=development

